/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smuralee;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {

    void printMessage(){
        log.info("Welcome to DSA examples using Java!!!");
    }
}
